target: ClosestWords.java homework.tex
	pdflatex homework.tex > /dev/null
	rm -f homework*.log homework*.aux homework*.out
	javac Main.java
	cat ordlista.txt testord.txt | java Main
	# labd (1) labb lagd land
	# dabbbhud (4) anbud dabba nabbad
